tasks:
  lint:
    command: eslint .
    platform: node
    inputs:
      # Config files anywhere within the project
      - "src/**/*.{js,mjs,json,ts,tsx}"
      - "*.{js,mjs,json,ts,tsx}"
      # Environment variables
      - "$ESLINT_CACHE"
      - "$ESLINT_*"
