tasks:
  svelte-check:
    command:
      - svelte-check
      - --tsconfig
      - ./tsconfig.json
    deps:
      - ~:svelte-kit-sync
    platform: node
  svelte-check-watch:
    extends: svelte-check
    args:
      - --watch
    local: true
  svelte-kit-sync:
    command:
      - svelte-kit
      - sync
    platform: node
