tasks:
  prettier:
    command: yarn prettier --write --check --ignore-path .gitignore --ignore-path ../../.gitignore --ignore-path ../../.prettierignore .
    options:
      runInCI: false
  prettierCheck:
    command: yarn prettier --check --ignore-path .gitignore --ignore-path ../../.gitignore --ignore-path ../../.prettierignore .
