name: CI (daily)

on:
  schedule:
    # Run at 7 AM AEST, some tests check if packages are up to date (e.g. `expo
    # doctor`). Without a schedule then random pull requests can fail.
    - cron: 0 17 * * *
  workflow_dispatch:

jobs:
  moon-ci:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Clone repo
        uses: actions/checkout@v4
        with:
          # Only fetch a single commit, so that `moon ci` is forced to run all
          # tasks rather than just ones based on a diff. (`fetch-depth: 1` is
          # the default, but since it's critical that it doesn't change)
          fetch-depth: 1

      - uses: ./.github/actions/setup-tools

      # Don't use `moon ci` because it will only run tasks with inputs that have
      # changed since the last commit.
      - run: moon ci
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
