name: CI (daily)

on:
  schedule:
    # Run at 7 AM AEST, some tests check if packages are up to date (e.g. `expo
    # doctor`). Without a schedule then random pull requests can fail.
    - cron: 0 17 * * *

jobs:
  moon-ci:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Clone repo
        uses: actions/checkout@v4
        # Intentionally omit `fetch-depth: 0` to force all targets to be run
        # instead of some being skipped due to `moon run <…> --affected`
        # behavior.

      - uses: ./.github/actions/setup-tools

      - run: moon ci
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
