name: CI (daily)

on:
  schedule:
    # Run at 7 AM AEST, some tests check if packages are up to date (e.g. `expo
    # doctor`). Without a schedule then random pull requests can fail.
    - cron: 0 17 * * *
  workflow_dispatch:

jobs:
  moon-ci:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Clone repo
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-tools

      # Don't use `moon ci` because it will only run tasks with inputs that have
      # changed since the last commit.
      - run: moon check -u --all
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
