name: Expo EAS Update
on:
  push:
    branches:
      - "main"
      - "releases/**"

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - name: 📦 Install dependencies
        uses: "moonrepo/setup-toolchain@v0"

      - name: 🚀 Publish update
        run: |
          moon run frontend:eas -- update --auto --non-interactive
          npx sentry-expo-upload-sourcemaps dist
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
