name: Expo EAS Build
on:
  workflow_dispatch:
    inputs:
      platform:
        description: Platform
        required: true
        default: all
        type: choice
        options:
          - ios
          - android
          - all
      profile:
        description: Profile
        required: true
        default: preview
        type: choice
        options:
          - preview
          - production

jobs:
  update:
    name: EAS Build
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Clone repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📦 Install dependencies
        uses: moonrepo/setup-toolchain@v0.3.1
        with:
          auto-install: true

      - name: 🚀 Build app
        run: moon run app:eas -- build --profile=${{ inputs.profile }} --platform=${{ inputs.platform }} --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          EXPO_PUBLIC_REPLICACHE_LICENSE_KEY: ${{ secrets.EXPO_PUBLIC_REPLICACHE_LICENSE_KEY }}
