name: Expo EAS Build
on:
  workflow_dispatch:
    inputs:
      platform:
        description: "Platform"
        required: true
        default: "ios"
        type: choice
        options:
          - ios
          - android
          - all
      profile:
        description: "Profile"
        required: true
        default: "preview"
        type: choice
        options:
          - preview
          - production

jobs:
  update:
    name: EAS Build
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - name: 📦 Install dependencies
        uses: "moonrepo/setup-toolchain@v0"

      - name: 🚀 Build app
        run: moon run frontend:eas -- build --profile=${{ inputs.profile }} --platform=${{ inputs.platform }} --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
