name: Production Vercel (frontend)

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_FRONTEND }}

on:
  push:
    branches:
      - "main"

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
      - uses: "moonrepo/setup-toolchain@v0"
      - name: Fetch Vercel secrets
        run: moon run frontend:vercel -- pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: moon run frontend:vercel -- build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: moon run frontend:vercel -- deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
