name: Production Vercel (api)

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_API }}

on:
  push:
    branches:
      - "main"

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - name: 📦 Install dependencies
        uses: "moonrepo/setup-toolchain@v0"

      - name: 🔑 Fetch Vercel secrets
        run: moon run api:vercel -- pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: 🚀 Build Project Artifacts
        run: moon run api:vercel -- build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: 🚀 Deploy Project Artifacts to Vercel
        run: moon run api:vercel -- deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
