name: Production DB migrate

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_WWW }}

on:
  push:
    branches:
      - "main"

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
      - uses: "moonrepo/setup-toolchain@v0"
      - name: Fetch Vercel secrets
        run: moon run frontend:vercel -- env pull --environment=production --token=${{ secrets.VERCEL_TOKEN }} .env.local
      - name: Run Drizzle migrations
        run: moon run frontend:migrate
