name: Release

on:
  push:
    branches:
      - main

concurrency:
  # Ensure only one build at a time, so that DB migrations, EAS releases, Vercel
  # deployments, all happen in sequence and results are more deterministic.
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  database:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Clone repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-tools

      - name: 🚀 Migrate database
        run: moon run app:dbMigrate --color --affected --remote
        env:
          DATABASE_URL: ${{ secrets.NEON_DATABASE_URL }}

  app-vercel:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_APP }}
    steps:
      - name: 🏗 Clone repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-tools

      - name: 🚀 Deploy to Vercel (production)
        run: moon run app:deployVercel --color --affected --remote
        env:
          EXPO_PUBLIC_REPLICACHE_LICENSE_KEY: ${{ secrets.EXPO_PUBLIC_REPLICACHE_LICENSE_KEY }}
          HHH_VERCEL_PROD:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

  static-vercel:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_STATIC }}
    steps:
      - name: 🏗 Clone repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-tools

      - name: 🚀 Deploy to Vercel (production)
        run: moon run static:deploy --color --affected --remote
        env:
          HHH_VERCEL_PROD:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

  app-eas-update:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Clone repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-tools

      - name: 🚀 Build and deploy
        run: moon run app:deployEasUpdate --color --affected --remote
        env:
          EXPO_PUBLIC_REPLICACHE_LICENSE_KEY: ${{ secrets.EXPO_PUBLIC_REPLICACHE_LICENSE_KEY }}
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
