name: Clear all Github actions caches
on:
  workflow_dispatch:

jobs:
  reset:
    name: Delete all caches
    runs-on: ubuntu-latest

    steps:
      - name: Clear caches
        uses: easimon/wipe-cache@v2
